/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kulabuha;


import com.google.common.math.LongMath;

public class HelloOtus {
    public static void main(String... args) {
        System.out.println(LongMath.ceilingPowerOfTwo(7));
    }
}
